dash/dash/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include, path


urlpatterns = [
    path('results/', include('results.urls')),
    path('admin/', admin.site.urls),
]

dash/results/urls.py
from django.urls import path

from . import views

app_name = 'results'
urlpatterns = [
    # ex: /results/
    path('', views.index, name='index'),

    # ex: /results/5/
    path('<int:result_id>/', views.detail, name='detail'),

    # ex: /results/log/?test_name=simple%20test
    path('log/', views.log, name='log'),

    # ex: /results/log_file/?test_name=simple%20test
    path('log_file/', views.log_file, name='log_file'),

    # ex: /results/get_file/?test_name=test1&app_name=Apply&run_name=Run1&name=screen.jpg
    path('get_file/', views.get_file, name='get_file'),

    # ex: /results/run/My_Run/
    path('run/<run_name>/', views.run, name='run'),

    # ex: /results/app/My_App/
    path('app/<app_name>/', views.app, name='app'),

    # ex: /results/team/My_Team/
    path('team/<team_name>/', views.team, name='team'),

    # ex: /results/app/My_App/TeamCity/
    path('app/<app_name>/<run_server>/', views.app, name='app'),

    # ex: /results/app/My_App/keep/5/
    path('app/<app_name>/keep/<int:keep_runs>/', views.keep, name='keep'),

    # ex: /results/delete/5/
    path('delete/<int:result_id>/', views.delete, name='delete'),

    # ex: /results/delete_oldest_runs_per_app_only_keep_newest/50/
    path('delete_oldest_runs_per_app_only_keep_newest/<int:number_of_runs_to_keep>/'
        , views.delete_oldest_runs_per_app_only_keep_newest
        , name='delete_oldest_runs_per_app_only_keep_newest'),

    # ex: /results/latest/
    path('latest/', views.latest, name='latest'),

    # ex: /results/latest/TeamCity
    path('latest/<run_server>/', views.latest, name='latest'),
]

dash/results/models.py
from django.db import models

from django.db.models.signals import post_delete
from django.dispatch import receiver

# Create your models here.

class Result(models.Model):
    test_name = models.CharField(max_length=200)
    app_name = models.CharField(max_length=50)
    test_passed = models.NullBooleanField(default=None)
    run_name = models.CharField(max_length=20)
    run_server = models.CharField(max_length=30)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=200, null=True, blank=True)
    team_name = models.CharField(max_length=20, default=None, blank=True, null=True)

class Artefact(models.Model):
    test_name = models.CharField(max_length=200)
    app_name = models.CharField(max_length=50)
    run_name = models.CharField(max_length=20)
    name = models.CharField(max_length=160)
    desc = models.CharField(max_length=200)
    document = models.FileField(upload_to='artefacts/%Y/%m/%d/', default=None)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

@receiver(post_delete, sender=Artefact)
def submission_delete(sender, instance, **kwargs):
    instance.document.delete(False)

dash/results/forms.py
from django import forms
from .models import Artefact

class ArtefactForm(forms.ModelForm):
    class Meta:
        model = Artefact
        fields = (
            'test_name',
            'app_name',
            'run_name',
            'name',
            'desc',
            'document',
        )

dash/results/views.py
# Create your views here.

from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from itertools import chain

from django.utils.http import urlencode

from .models import Result
from .models import Artefact
from .forms import ArtefactForm
from django.views.decorators.csrf import csrf_exempt
from django.core.files.storage import FileSystemStorage

import os

def index(request):
    return latest(request)

def detail(request, result_id):
    try:
        result = Result.objects.get(pk=result_id)
    except Result.DoesNotExist:
        result = None

    page_title = 'Result id ' + str(result_id)
    page_heading = page_title

    artefactsLab = None
    if (result):
        result.test_status = _get_test_status(result.test_passed)
        result.duration = result.date_modified - result.date_created
        if (result.test_status == 'pend'):
            result.date_modified = ''
            result.duration = ''
        artefactsLab = _get_artefacts(result)

    if artefactsLab:
        for artefact in artefactsLab:
            artefact.url = _artefact_url(artefact.test_name, artefact.app_name, artefact.run_name, artefact.name)
            artefact.image = _is_image(artefact.name)
            artefact.duration, artefact.duration_text = _get_duration(result.date_created, artefact.date_created)


    context = {
        'page_title': page_title,
        'page_heading': page_heading,
        'result': result,
        'artefacts': artefactsLab,
    }

    return render(request, 'results/detail.html', context)

def _get_artefacts(result):
    try:
        artefactsLab = Artefact.objects.filter(test_name=result.test_name, app_name=result.app_name, run_name=result.run_name)
    except Artefact.DoesNotExist:
        artefactsLab = None
    return artefactsLab

# /results/get_file/?test_name=test1&app_name=Apply&run_name=Run1&name=screen.jpg
def _artefact_url(test_name, app_name, run_name, name):
    return my_reverse('results:get_file',
        query_kwargs={
                'test_name': test_name,
                'app_name': app_name,
                'run_name': run_name,
                'name': name,
            }
        )

def _is_image(filename):
    if 'image' in _get_mime_type(filename):
        return True
    return False

def my_reverse(viewname, kwargs=None, query_kwargs=None):
    url = reverse(viewname, kwargs=kwargs)

    if query_kwargs:
        return u'%s?%s' % (url, urlencode(query_kwargs))

    return url


def log(request):
    result = Result( test_name = request.GET.get('test_name', None) )
    result.app_name = request.GET.get('app_name', None)
    test_passed_text = request.GET.get('test_passed', None)
    result.test_passed = _convert_test_passed_text_to_true_false_or_none_meaning_pend(test_passed_text)
    result.run_name = request.GET.get('run_name', None)
    result.run_server = request.GET.get('run_server', None)
    result.message = request.GET.get('message', None)
    result.team_name = request.GET.get('team_name', None)

    error = returnErrorMessageIfMandatoryFieldNone('test_name', result.test_name)
    error += returnErrorMessageIfMandatoryFieldNone('app_name', result.app_name)
    error += returnErrorMessageIfMandatoryFieldNone('run_name', result.run_name)
    error += returnErrorMessageIfMandatoryFieldNone('run_server', result.run_server)
    if (error):
        return render(request, 'results/log.html', { 'page_title': 'Error', 'error': error })

    priorResultLab = Result.objects.filter(run_name = result.run_name, app_name=result.app_name, test_name=result.test_name)
    if (priorResultLab):
        priorResult = priorResultLab[0]
        priorResult.test_passed = result.test_passed
        priorResult.message = result.message
        priorResult.save()
        result = priorResult
    else:
        result.save(force_insert=True)

    result.test_status = _get_test_status(result.test_passed)
    info = ''
    page_title = 'Log result'
    page_heading = 'Test logged ok'
    context = {
        'page_title': page_title,
        'page_heading': page_heading,
        'result': result,
        'info': info,
        'error': error,
    }

    return render(request, 'results/log.html', context)


# https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html
# https://gearheart.io/blog/how-to-upload-files-with-django/
@csrf_exempt
def log_file(request):
    if request.method != 'POST':
        return _log_file_form(request)

    artefact = Artefact( test_name = request.POST.get('test_name', None) )
    artefact.app_name = request.POST.get('app_name', None)
    artefact.run_name = request.POST.get('run_name', None)
    artefact.name = request.POST.get('name', None)
    artefact.desc = request.POST.get('desc', None)

    error = returnErrorMessageIfMandatoryFieldNone('test_name', artefact.test_name)
    error += returnErrorMessageIfMandatoryFieldNone('app_name', artefact.app_name)
    error += returnErrorMessageIfMandatoryFieldNone('run_name', artefact.run_name)
    error += returnErrorMessageIfMandatoryFieldNone('name', artefact.name)
    error += returnErrorMessageIfMandatoryFieldNone('desc', artefact.desc)
    if (error):
        return render(request, 'results/log_file.html', { 'page_title': 'Error', 'error': error })

    # upload = request.FILES['document']
    # fs = FileSystemStorage()
    # filename = fs.save(f'artifacts/{artefact.app_name}/{artefact.run_name}/{artefact.test_name}/{artefact.name}', upload)
    # uploaded_file_url = fs.url(filename)        

    form = ArtefactForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()

    # this section proves to a unit test that the file was uploaded
    content = ''
    if artefact.name == 'test.test':
        f = request.FILES['document']
        for chunk in f.chunks():
            content = chunk.decode("utf-8")

    url = _artefact_url(artefact.test_name, artefact.app_name, artefact.run_name, artefact.name)

    page_title = 'Log file'
    page_heading = 'File logged ok'
    error = ''
    context = {
        'page_title': page_title,
        'page_heading': page_heading,
        'url': url,
        'name': artefact.name,
        'desc': artefact.desc,
        'content': content,
        'error': error,
    }
    return render(request, 'results/log_file.html', context)

def _log_file_form(request):
    form = ArtefactForm()
    context = { 
        'page_title': 'Log file',
        'page_heading': 'Upload test artefact',
        'form': form,
    }
    return render(request, 'results/log_file_form.html', context)

def get_file(request):
    test_name = request.GET.get('test_name', None)
    app_name = request.GET.get('app_name', None)
    run_name = request.GET.get('run_name', None)
    name = request.GET.get('name', None)

    try:
        artefactLab = Artefact.objects.filter(test_name=test_name, app_name=app_name, run_name=run_name, name=name)
    except Artefact.DoesNotExist:
        artefactLab = None

    if not artefactLab:
        return HttpResponse('File does not exist')

    with artefactLab[0].document.open(mode='rb') as content_file:
         content = content_file.read()

    return HttpResponse(content, content_type=_get_mime_type(name))

def _get_mime_type(path):
    filename, file_extension = os.path.splitext(path)
    file_extension = file_extension.lower()
    if file_extension == '.jpg':
        return 'image/jpeg'
    if file_extension == '.png':
        return 'image/png'
    if file_extension == '.html':
        return 'text/html'
    if file_extension == '.json':
        return 'application/json'
    return 'text/plain'

def _convert_test_passed_text_to_true_false_or_none_meaning_pend(test_passed_text):
    if (test_passed_text == None):
        return None
    if (test_passed_text == ''):
        return None
    test_passed_text = test_passed_text.lower()
    if (test_passed_text == 'true' or
        test_passed_text == 'pass' or
        test_passed_text == 'passed' or
        test_passed_text == 'yes' or
        test_passed_text == 'ok'):
        return True
    if (test_passed_text == 'pend' or
        test_passed_text == 'pending' or
        test_passed_text == 'running' or
        test_passed_text == 'started'):
        return None
    return False

def _get_test_status(test_passed):
    if (test_passed == None):
        return 'pend'
    if (test_passed):
        return 'pass'
    return 'fail'

def returnErrorMessageIfMandatoryFieldNone(field_name, field_value):
    if (field_value):
        return ''
    return 'Test result not logged - must supply ' + field_name + '! '

def run(request, run_name):
    run_results = Result.objects.filter(run_name=run_name)

    for result in run_results:
        result.test_status = _get_test_status(result.test_passed)
        result.duration, result.duration_text = _get_duration(result.date_created, result.date_modified)
        if (result.test_status == 'pend'):
            result.duration = ''
            result.date_modified = ''

    total_tests, total_failed, total_pending = _get_status_for_run(run_results, run_name)
    total_passed = total_tests - total_failed - total_pending

    overall_status = 'pass'
    if (total_pending > 0):
        overall_status = 'pend'
    if (total_failed > 0):
        overall_status = 'fail'

    page_title = run_name

    page_heading = 'Results for run ' + run_name

    summary = summaryBuilder()
    summary.append_non_zero_value(total_passed, 'passed')
    summary.append_non_zero_value(total_failed, 'failed')

dash/results/templates/results/app.html
{% extends "public/base.html" %}

{% block content %}

{% if app_results %}
    <h1 class="{{app_status}}">App status: {{ app_status }}<h1>
    <h2>{{ page_heading }}</h2>
    <table id="app_results_table">
        <tr>
            <th></th>
            <th></th>
            <th>Run duration</th>
            <th></th>
            <th>Start</th>
            <th>End</th>
        </tr>
    {% for result in app_results reversed %}
        <tr>
            <td>
                <a href="{% url 'results:run' result.run_name %}" class="normal">{{ result.run_name }}</a>
            </td>
            <td>
                <a href="{% url 'results:run' result.run_name %}" name="run_status" class="{{result.run_status}}">{{result.run_status_desc}}</a>
            </td>
            <td duration_hires="{{result.duration}}">
                {{result.duration_text}}
            </td>
            <td>
                <a href="{% url 'results:app' app_name result.run_server %}" class="normal">{{ result.run_server }}</a>
            </td>
            <td start_hires="{{result.start | date:"d M Y H:i:s.u"}}">
                {{result.start | date:"d M Y H:i:s"}}
            </td>
            <td end_hires="{{result.end | date:"d M Y H:i:s.u"}}">
                {{result.end | date:"d M Y H:i:s"}}
            </td>
            <!-- ~ End Row -->
        </tr>
    {% endfor %}
    </table>
    <h4>{{ app_status_desc }}</h4>
{% else %}
    <p>No results are available.</p>
    <h4><a href="{% url 'results:latest' %}" class="normal">See all the latest results here</a></h4>

{% endif %}

{% endblock %}

dash/results/templates/results/delete.html
{% extends "public/base.html" %}

{% block content %}

    <h2>{{ page_heading }}</h2>

    {% if artefacts_deleted %}
    <p>{{ artefacts_deleted }} test artefacts were also deleted</p>
    {% endif %}

{% endblock %}

dash/results/templates/results/delete_oldest.html
{% extends "public/base.html" %}

{% block content %}

    <h2>{{ page_heading }}</h2>

    <p>Deleted {{runs_deleted_count}} runs</p>

{% endblock %}

dash/results/templates/results/detail.html
{% extends "public/base.html" %}

{% block content %}

{% if result %}
    <h2>{{ page_heading }}</h2>
    <table id="result_detail">
        <tr>
            <td>App</td>
            <td class="bold"><a href="{% url 'results:app' result.app_name %}" class="normal">{{ result.app_name }}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Test</td>
            <td class="bold">{{result.test_name}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Status</td>
            <td class="bold{{result.test_status}}">{{result.test_status}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Run Name</td>
            <td class="bold"><a href="{% url 'results:run' result.run_name %}" class="normal">{{ result.run_name }}</a></td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Run Server</td>
            <td class="bold"><a href="{% url 'results:latest' result.run_server %}" class="normal">{{ result.run_server }}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Start</td>
            <td class="bold">{{result.date_created | date:"d M Y H:i:s.u"}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>End</td>
            <td class="bold">{{result.date_modified | date:"d M Y H:i:s.u"}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Duration</td>
            <td class="bold">{{result.duration}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Team Name</td>
            <td class="bold">{{result.team_name}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Message</td>
            <td class="bold">{{result.message|default_if_none:''}}</td>
            <!-- ~ End Row -->
        </tr>
    </table>
    <p></p>
    {% if artefacts %}
    <table id="files_detail">
    {% for artefact in artefacts %}
        <tr>
            <td class="bold" name="OffsetFromTestStart">{{artefact.duration_text}}</td>
            <td class="bold" name="ArtefactDesc">{{artefact.desc}}</td>
        {% if artefact.image %}
            <td class="bold" name="Artefact">{{artefact.name}}<br/><a href="{{artefact.url}}"><img src="{{artefact.url}}"></a></td>
        {% else %}
            <td class="bold" name="Artefact"><a href="{{artefact.url}}" class="normal">{{artefact.name}}</a></td>
        {% endif %}
        </tr>
    {% endfor %}
    </table>
    {% endif %}
{% else %}
    <p>No results are available.</p>
    <h4><a href="{% url 'results:latest' %}" class="normal">See all the latest results here</a></h4>
{% endif %}
{% endblock %}

dash/results/templates/results/keep.html
{% extends "public/base.html" %}

{% block content %}

    <h2>{{ page_heading }}</h2>

    <p>{{ message }}</p>

{% endblock %}

dash/results/templates/results/latest.html
{% extends "public/base.html" %}

{% block content %}

{% if latest_results %}
    <h2>{{ page_heading }}</h2>
    <table id="latest_results_table">
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th>Start</th>
            <th>Duration</th>
        </tr>
    {% for result in latest_results reversed %}
        <tr id="result_id_{{result.id}}">
            <td>
                <a href="{% url 'results:run' result.run_name %}" name="run_status" class="{{result.run_status}}">{{result.total_tests}} tests{{result.failed_message}}</a>
            </td>
            <td>
                <a href="{% url 'results:app' result.app_name %}" class="normal">{{ result.app_name }}</a>
            </td>
            <td>
                <a href="{% url 'results:run' result.run_name %}" class="normal">{{ result.run_name }}</a>
            </td>
            <td>
                <a href="{% url 'results:latest' result.run_server %}" class="normal">{{result.run_server}}</a>
            </td>
            <td>
                {{result.start | date:"d M Y H:i:s"}}
            </td>
            <td hires_duration="{{result.duration}}">
                {{result.duration_text}}
            </td>
            <!-- ~ End Row -->
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No results are available.</p>
{% endif %}

{% endblock %}

dash/results/templates/results/log.html
{% extends "public/base.html" %}

{% block content %}

{% if error %}
    <h4>{{error}}</h4>
{% else %}
    <h2>{{ page_heading }}</h2>
    <table id="result_detail">
        <tr>
            <!-- For unit tests: test_result_id is {{result.id}} -->
            <td>Result id</td>
            <td class="bold">{{result.id}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>App</td>
            <td class="bold"><a href="{% url 'results:app' result.app_name %}" class="normal">{{ result.app_name }}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Test</td>
            <td class="bold">{{result.test_name}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Status</td>
            <td class="bold{{result.test_status}}">{{result.test_status}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Run Name</td>
            <td class="bold"><a href="{% url 'results:run' result.run_name %}" class="normal">{{ result.run_name }}</a></td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Run Server</td>
            <td class="bold"><a href="{% url 'results:latest' result.run_server %}" class="normal">{{ result.run_server }}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Log Date</td>
            <td class="bold">{{result.date_created | date:"d M Y H:i:s.u"}}</td>
            <!-- ~ End Row -->
        </tr>
        <tr>
            <td>Message</td>
            <td class="bold">{{result.message|default_if_none:''}}</td>
            <!-- ~ End Row -->
        </tr>
    </table>
    <p>{{info}}</p>
{% endif %}

{% endblock %}

dash/results/templates/results/log_file.html
{% extends "public/base.html" %}

{% block content %}

{% if error %}
    <h4>{{error}}</h4>
{% else %}
    <h2>{{ page_heading }}</h2>
    <p>name: {{ name }}</p>
    <p>File desc: {{ desc }}</p>
    <p>Artefact url: {{ url|safe }}</p>
{% endif %}

 {% if content %}
 <p></p>
 <p>File content: {{ content }}</p>
 {% endif %}


{% endblock %}

dash/results/templates/results/log_file_form.html
{% extends "public/base.html" %}

{% block content %}

{% if error %}
    <h4>{{error}}</h4>
{% else %}
    <h2>{{ page_heading }}</h2>
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
{% endif %}

<p><a href="{% url 'results:index' %}">Return to home</a></p>

{% endblock %}

dash/results/templates/results/run.html
{% extends "public/base.html" %}

{% block content %}

{% if run_results %}
    <h2>{{ page_heading }}</h2>
    <h4 class="{{ overall_status }}">{{ page_summary }}</h4>
    <table id="run_results_table">
        <tr>
            <th></th>
            <th></th>
            <th></th>
            <th>Duration</th>
            <th>Start</th>
            <th>End</th>
            <th>Message</th>
        </tr>
    {% for result in run_results %}
        <tr id="result_id_{{result.id}}">
            <td>
                <a href="{% url 'results:app' result.app_name %}" class="normal">{{ result.app_name }}</a>
            </td>
            <td>
                <a href="{% url 'results:detail' result.id %}" class="{{result.test_status}}">{{result.test_status}}</a>
            </td>
            <td>
                {{result.test_name}}
            </td>
            <td name="duration" duration_hires="{{result.duration}}">
                {{result.duration_text}}
            </td>
            <td name="start" start_hires="{{result.date_created | date:"d M Y H:i:s.u"}}">
                {{result.date_created | date:"d M Y H:i:s"}}
            </td>
            <td name="end" end_hires="{{result.date_modified | date:"d M Y H:i:s.u"}}">
                {{result.date_modified | date:"d M Y H:i:s"}}
            </td>
            <td name="message">
                {{result.message|default_if_none:''}}
            </td>
            <!-- ~ End Row -->
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No results are available.</p>
    <h4><a href="{% url 'results:latest' %}" class="normal">See all the latest results here</a></h4>
{% endif %}

{% endblock %}

dash/results/templates/results/team.html
{% extends "public/base.html" %}

{% block content %}

    <h2>{{ page_heading }}</h2>

{% endblock %}